---
title: "MultipleTotalMassResult"
author: "Jianhui Gao"
date: "10/9/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = "~/Desktop/SyntheticSurrogateAnalysis/Data/")
library(ggplot2)
library(dplyr)
library(data.table)
library(hudson)

# my own gmirror plot
ggmirror <- function(top, bottom, tline, bline, chroms = c(1:22, "X", "Y"),log10=TRUE, 
                    yaxis, opacity=1, annotate_snp, annotate_p, toptitle=NULL, 
                    bottomtitle=NULL, highlight_snp, highlight_p, highlighter="red", 
                    chrcolor1="#AAAAAA", chrcolor2="#4D4D4D", chrcolor3, chrcolor4, freey=TRUE, 
                    background="variegated", chrblocks=FALSE, file="gmirror", 
                    type="png", hgt=7, hgtratio=0.5, wi=12, res=300 ){
  
  #Sort data
  topn <- names(top)
  bottomn <- names(bottom)
  top$Location <- "Top"
  bottom$Location <- "Bottom"
  
  # Check file formats
  if(!identical(topn, bottomn)){stop("Please ensure both inputs have the same metadata columns.")}
  
  d <- as.data.frame(rbind(top, bottom))
  
  d$POS <- as.numeric(as.character(d$POS))
  d$CHR <- droplevels(factor(d$CHR, levels = as.character(chroms)))
  d <- d[d$CHR %in% chroms, ]
  d_order <- d[order(d$CHR, d$POS), ]
  d_order$pos_index <- seq.int(nrow(d_order))
  d_order_sub <- d_order[, c("SNP", "CHR", "POS", "pvalue", "pos_index")]

  #Set up dataframe with color and position info
  maxRows <- by(d_order_sub, d_order_sub$CHR, function(x) x[which.max(x$pos_index),])
  minRows <- by(d_order_sub, d_order_sub$CHR, function(x) x[which.min(x$pos_index),])
  milimits <- do.call(rbind, minRows)
  malimits <- do.call(rbind, maxRows)
  lims <- merge(milimits, malimits, by="CHR")
  names(lims) <- c("Color", "snpx", "px", "posx", "posmin", "snpy", "py", "posy", "posmax")
  lims$av <- (lims$posmin + lims$posmax)/2
  lims <- lims[order(lims$Color),]
  lims$shademap <- rep(c("shade_ffffff", "shade_ebebeb"), length.out=nrow(lims), each=1)

  #Set up colors
  nchrcolors <- nlevels(factor(lims$Color))

  #Color by CHR
  colnames(d_order)[2] <- "Color"
  newcols <-c(rep(x=c(chrcolor1, chrcolor2), length.out=nchrcolors, each=1), "#FFFFFF", "#EBEBEB")
  newcols2 <-c(rep(x=c(chrcolor3, chrcolor4), length.out=nchrcolors, each=1), "#FFFFFF", "#EBEBEB")
  names(newcols) <-c(levels(factor(lims$Color)), "shade_ffffff", "shade_ebebeb")

  #Info for y-axis
  if(log10==TRUE){
    d_order$pval <- -log10(d_order$pvalue)
    yaxislab1 <- expression(paste("-log"[10], "(p-value)", sep=""))
    yaxislab2 <- expression(paste("-log"[10], "(p-value)", sep=""))
    if(!missing(tline)) {tredline <- -log10(tline)}
    if(!missing(bline)) {bredline <- -log10(bline)}
  } else {
    d_order$pval <- d_order$pvalue
    yaxislab1 <- yaxis[1]
    yaxislab2 <- yaxis[2]
    if(!missing(tline)) {tredline <- tline}
    if(!missing(bline)) {bredline <- bline}
  }
  yaxismax1 <- ifelse(freey==FALSE, max(d_order$pval[which(d_order$pval< Inf)]), max(d_order$pval[which(d_order$pval< Inf) & d_order$Location=="Top"]))
  yaxismax2 <- ifelse(freey==FALSE, max(d_order$pval[which(d_order$pval< Inf)]), max(d_order$pval[which(d_order$pval< Inf) & d_order$Location=="Bottom"]))
  yaxismin1 <- ifelse(freey==FALSE, 0, min(d_order$pval[d_order$Location=="Top"]))
  yaxismin2 <- ifelse(freey==FALSE, 0, min(d_order$pval[d_order$Location=="Bottom"]))
  
  #Theme options
  backpanel1 <- ifelse(background=="white", "NULL", "geom_rect(data = lims, aes(xmin = posmin-.5, xmax = posmax+.5, ymin = yaxismin1, ymax = Inf, fill=factor(shademap)), alpha = 0.5)" )
  backpanel2 <- ifelse(background=="white", "NULL", "geom_rect(data = lims, aes(xmin = posmin-.5, xmax = posmax+.5, ymin = yaxismin2, ymax = Inf, fill=factor(shademap)), alpha = 0.5)" )
  
  #Start plotting
  #TOP PLOT
  p1 <- ggplot() + eval(parse(text=backpanel1))
  #Add shape info if available
  if("Shape" %in% topn){
    p1 <- p1 + geom_point(data=d_order[d_order$Location=="Top",], aes(x=pos_index, y=pval, color=factor(Color), shape=factor(Shape)), alpha=opacity)
  } else {
    p1 <- p1 + geom_point(data=d_order[d_order$Location=="Top",], aes(x=pos_index, y=pval, color=factor(Color)), alpha=opacity)
  }
  p1 <- p1 + scale_x_continuous(breaks=lims$av, labels=lims$Color, expand=c(0,0))
  if(chrblocks==TRUE){
    p1 <- p1 + geom_rect(data = lims, aes(xmin = posmin-.5, xmax = posmax+.5, ymin = -Inf, ymax = min(d_order$pval), fill=as.factor(Color)), alpha = 1)
  }
  p1 <- p1 + scale_colour_manual(name = "Color", values = newcols) + scale_fill_manual(name = "Color", values = newcols)
  p1 <- p1 + theme(panel.grid.minor.x = element_blank(), panel.grid.major.x=element_blank(), axis.title.x=element_blank(), legend.position="top", legend.title=element_blank())

  #BOTTOM PLOT
  p2 <- ggplot() + eval(parse(text=backpanel2))
  #Add shape info if available
  if("Shape" %in% bottomn){
    p2 <- p2 + geom_point(data=d_order[d_order$Location=="Bottom",], aes(x=pos_index, y=pval, color=factor(Color), shape=factor(Shape)), alpha=opacity)
  } else {
    p2 <- p2 + geom_point(data=d_order[d_order$Location=="Bottom",], aes(x=pos_index, y=pval, color=factor(Color)), alpha=opacity)
  }
  p2 <- p2 + scale_x_continuous(breaks=lims$av, labels=lims$Color, expand=c(0,0))
  if(chrblocks==TRUE){
    p2 <- p2 + geom_rect(data = lims, aes(xmin = posmin-.5, xmax = posmax+.5, ymin = -Inf, ymax = min(d_order$pval), fill=as.factor(Color)), alpha = 1)
  }  
  p2 <- p2 + scale_colour_manual(name = "Color", values = newcols2) + scale_fill_manual(name = "Color", values = newcols)
  p2 <- p2 + theme(axis.text.x=element_text(angle=90), panel.grid.minor.x = element_blank(), panel.grid.major.x=element_blank(), axis.title.x=element_blank(), legend.position="bottom", legend.title=element_blank())

  #Highlight if given
  if(!missing(highlight_snp)){
    if("Shape" %in% topn){
      p1 <- p1 + geom_point(data=d_order[d_order$SNP %in% highlight_snp & d_order$Location=="Top", ], aes(x=pos_index, y=pval, shape=Shape), colour=highlighter)
      p1 <- p1 + guides(shape = guide_legend(override.aes = list(colour = "black")))
    } else {
      p1 <- p1 + geom_point(data=d_order[d_order$SNP %in% highlight_snp & d_order$Location=="Top", ], aes(x=pos_index, y=pval), colour=highlighter)
    }
    if("Shape" %in% bottomn){
      p2 <- p2 + geom_point(data=d_order[d_order$SNP %in% highlight_snp & d_order$Location=="Bottom", ], aes(x=pos_index, y=pval, shape=Shape), colour=highlighter)
      p2 <- p2 + guides(shape = guide_legend(override.aes = list(colour = "black")))
    } else {
      p2 <- p2 + geom_point(data=d_order[d_order$SNP %in% highlight_snp & d_order$Location=="Bottom", ], aes(x=pos_index, y=pval), colour=highlighter)
    }
  }
  if(!missing(highlight_p)){
    if("Shape" %in% topn){
      p1 <- p1 + geom_point(data=d_order[d_order$pvalue < highlight_p[1] & d_order$Location=="Top", ], aes(x=pos_index, y=pval, shape=Shape), colour=highlighter)
      p1 <- p1 + guides(shape = guide_legend(override.aes = list(colour = "black")))
    } else {
      p1 <- p1 + geom_point(data=d_order[d_order$pvalue < highlight_p[1] & d_order$Location=="Top", ], aes(x=pos_index, y=pval), colour=highlighter)
    }
    if("Shape" %in% bottomn){
      p2 <- p2 + geom_point(data=d_order[d_order$pvalue < highlight_p[2] & d_order$Location=="Bottom", ], aes(x=pos_index, y=pval, shape=Shape), colour=highlighter)
      p2 <- p2 + guides(shape = guide_legend(override.aes = list(colour = "black")))
    } else {
      p2 <- p2 + geom_point(data=d_order[d_order$pvalue < highlight_p[2] & d_order$Location=="Bottom", ], aes(x=pos_index, y=pval), colour=highlighter)
    }
  }
  #Add pvalue threshold line
  if(!missing(tline)){
    for(i in 1:length(tline)){
      p1 <- p1 + geom_hline(yintercept = tredline[i], colour="red")
    }
  }
  if(!missing(bline)){
    for(i in 1:length(bline)){
      p2 <- p2 + geom_hline(yintercept = bredline[i], colour="red")
    }
  }
  #Annotate
  if(!missing(annotate_p)){
    if (!requireNamespace(c("ggrepel"), quietly = TRUE)==TRUE) {
      print("Consider installing 'ggrepel' for improved text annotation")
      p1 <- p1 + geom_text(data=d_order[d_order$pvalue < annotate_p[1] & d_order$Location=="Top",], aes(pos_index,pval,label=SNP))
      p2 <- p2 + geom_text(data=d_order[d_order$pvalue < annotate_p[2] & d_order$Location=="Bottom",], aes(pos_index,pval,label=SNP))
    } else {
      p1 <- p1 + ggrepel::geom_text_repel(data=d_order[d_order$pvalue < annotate_p[1] & d_order$Location=="Top",], aes(pos_index,pval,label=SNP))
      p2 <- p2 + ggrepel::geom_text_repel(data=d_order[d_order$pvalue < annotate_p[2] & d_order$Location=="Bottom",], aes(pos_index,pval,label=SNP))
    }
  }
  if(!missing(annotate_snp)){
    if (!requireNamespace(c("ggrepel"), quietly = TRUE)==TRUE){
      print("Consider installing 'ggrepel' for improved text annotation")
      p1 <- p1 + geom_text(data=d_order[d_order$SNP %in% annotate_snp & d_order$Location=="Top",], aes(pos_index,pval,label=SNP))
      p2 <- p2 + geom_text(data=d_order[d_order$SNP %in% annotate_snp & d_order$Location=="Bottom",], aes(pos_index,pval,label=SNP))
    } else {
      p1 <- p1 + ggrepel::geom_text_repel(data=d_order[d_order$SNP %in% annotate_snp & d_order$Location=="Top",], aes(pos_index,pval,label=SNP))
      p2 <- p2 + ggrepel::geom_text_repel(data=d_order[d_order$SNP %in% annotate_snp & d_order$Location=="Bottom",], aes(pos_index,pval,label=SNP))
    }
  }
  #Add title and y axis title
  p1 <- p1 + ylab(yaxislab1)
  p2 <- p2 + ylab(yaxislab2)
  
  #Format
  if(chrblocks==TRUE){
    if(freey==TRUE){
      print("Sorry, drawing chrblocks with freey=TRUE is currently unsupported and will be ignored.")
    } else {
      p1 <- p1+theme(axis.text.x = element_text(vjust=1),axis.ticks.x = element_blank())+ylim(c(yaxismin1,yaxismax1))
      p2 <- p2+scale_y_reverse(limits=c(yaxismax2, yaxismin2)) + theme(axis.text.x = element_blank(),axis.ticks.x = element_blank())
    }
  } else {
    p1 <- p1+theme(axis.text.x = element_text(vjust=1),axis.ticks.x = element_blank())+ scale_y_continuous(limits=c(yaxismin1, yaxismax1),expand=expansion(mult=c(0,0.1)))
    p2 <- p2+scale_y_reverse(limits=c(yaxismax2,yaxismin2), expand=expansion(mult=c(0.1,0))) + theme(axis.text.x = element_blank(),axis.ticks.x = element_blank())
  }

  if(background=="white"){
    p1 <- p1 + theme(panel.background = element_rect(fill="white"))
    p2 <- p2 + theme(panel.background = element_rect(fill="white"))
  }
  p1 <- p1 + guides(fill="none", color="none")
  p2 <- p2 + guides(fill="none", color="none")
  #Save
  print(paste0("Saving plot to ", file, ".", type))
  p <- grid.arrange(arrangeGrob(p1, top=toptitle), arrangeGrob(p2, bottom=bottomtitle), padding=0, heights=c(hgtratio,1-hgtratio))
  ggsave(p, filename=paste0(file, ".", type), dpi=res, units="in", height=hgt, width=wi)
}

white <- read.table("~/Desktop/SyntheticSurrogateAnalysis/Data/Ancestry.tab", header = TRUE)
file <- read.table("~/Desktop/SyntheticSurrogateAnalysis/Data/CombinedTotalMass.tab", header=TRUE, sep="\t")
in_id <- read.table("~/Desktop/SyntheticSurrogateAnalysis/Data/final.king.cutoff.in.id", header=TRUE) %>% pull(FID)
out_id <- read.table("~/Desktop/SyntheticSurrogateAnalysis/Data/final.king.cutoff.out.id", header=TRUE)%>% pull(FID)

cov_id <- c("f.21022.0.0","f.22001.0.0","f.50.0.0","f.23098.0.0","f.23104.0.0") #age,sex,height, weight, BMI
# split data into train and test

cov_column <- file %>% select(cov_id)
bim <- read.table("~/Desktop/SyntheticSurrogateAnalysis/Data/final.bim", header = TRUE)
```

# Android total mass (23248)
```{r}
pheno_id <- "f.23248.2.0"

train <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% out_id) %>% tidyr::drop_na(pheno_id) %>% tidyr::drop_na(all_of(cov_id)) %>% select(pheno_id, cov_id) %>% filter(f.23248.2.0 > 100)
test <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% in_id) %>% tidyr::drop_na(all_of(cov_id))%>% select(f.eid,pheno_id, cov_id)  %>% tidyr::drop_na(pheno_id) %>% filter(f.23248.2.0 > 100)

# Random Forest model
model.rf <- ranger::ranger(
  data = train,
  as.formula(paste0(pheno_id, "~."))
)
get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
yhat <- predict(model.rf, data = train %>% select(-pheno_id))$predictions
train$yhat <- yhat
p1 <- train %>% rename(pheno = pheno_id) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 18, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("Model-building dataset")+xlim(c(0,20))+ylim(c(0,20))

yhat <- predict(model.rf, data = test %>% select(-f.eid,-pheno_id))$predictions
test$yhat <- yhat
p2 <- test %>% rename(pheno = pheno_id) %>% filter(!is.na(pheno)) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 18, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("GWAS dataset")+xlim(c(0,20))+ylim(c(0,20))

ggpubr::ggarrange(p1, p2)
```

```{r}
result <- readRDS(paste0("~/Desktop/SyntheticSurrogateAnalysis/Data/pheno=", pheno_id, "_result.rds"))
result[,2:7] <-  mutate_all(result[,2:7], function(x) as.numeric(x))


index1 <- which(result$marginal.p<5e-8)
cat ("Total Number of Discovery by marginal GWAS:", length(index1), "\n")
index2 <- which(result$bi.p<5e-8)
cat ("Total Number of Discovery by SynSurr:", length(index2), "\n")
index <- c(index1, index2)
cat("Number of marginal SNPs recovered:", sum(index1 %in% index2),"\n")
cat("Number of New Discovery:", sum(!(index2 %in% index1)),"\n")
cat("Average Chisq of marginal GWAS:", mean((result$marginal.beta[index]/result$marginal.se[index])^2),"\n")
cat("Average Chisq of SynSurr:", mean((result$bi.beta[index]/result$bi.se[index])^2),"\n")
cat("RE (Mean Square Standard Error)", mean((result$marginal.se[index])^2/(result$bi.se[index])^2))
```
```{r}
#library(hudson)
result <- result %>% inner_join(bim, by = "rsid") %>% rename(SNP = rsid, POS = BP)

#write.csv(result %>% filter(marginal.p<1e-5|bi.p<1e-5) %>% select(rsid, CHR, BP, Ref, Alt, marginal.beta,
#                                                                  marginal.se, marginal.p, bi.beta,
#                                                                  bi.se, bi.p), file = "small_p.csv",
#          row.names = FALSE, quote = FALSE)

gwas.b <- result %>% select(SNP, CHR, POS, marginal.p) %>% rename(pvalue = marginal.p)
gwas.t <- result %>% select(SNP, CHR, POS, bi.p) %>% rename(pvalue = bi.p)
ggmirror(top=gwas.t, bottom=gwas.b, tline=5e-8, bline=5e-8, toptitle="SynSurr GWAS", bottomtitle = "Standard GWAS", chrcolor1 = "#00FF00", chrcolor2 = "#006600", chrcolor4 = "#0000CC", chrcolor3 = "#0099FF")
```

# Arms total mass (23260)
```{r}
pheno_id <- "f.23260.2.0"
train <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% out_id) %>% tidyr::drop_na(pheno_id) %>% tidyr::drop_na(all_of(cov_id)) %>% select(pheno_id, cov_id) %>% filter(f.23260.2.0 > 100)
test <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% in_id) %>% tidyr::drop_na(all_of(cov_id))%>% select(f.eid,pheno_id, cov_id)  %>% tidyr::drop_na(pheno_id) %>% filter(f.23260.2.0 > 100)

# Random Forest model
model.rf <- ranger::ranger(
  data = train,
  as.formula(paste0(pheno_id, "~."))
)

yhat <- predict(model.rf, data = train %>% select(-pheno_id))$predictions
train$yhat <- yhat
p1 <- train %>% rename(pheno = pheno_id) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 20, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("Model-building dataset")+xlim(c(0,22))+ylim(c(0,22))

yhat <- predict(model.rf, data = test %>% select(-f.eid,-pheno_id))$predictions
test$yhat <- yhat
p2 <- test %>% rename(pheno = pheno_id) %>% filter(!is.na(pheno)) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 20, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("GWAS dataset")+xlim(c(0,22))+ylim(c(0,22))

ggpubr::ggarrange(p1, p2)
```

```{r}
result <- readRDS(paste0("~/Desktop/SyntheticSurrogateAnalysis/Data/pheno=", pheno_id, "_result.rds"))
result[,2:7] <-  mutate_all(result[,2:7], function(x) as.numeric(x))

index1 <- which(result$marginal.p<5e-8)
cat ("Total Number of Discovery by marginal GWAS:", length(index1), "\n")
index2 <- which(result$bi.p<5e-8)
cat ("Total Number of Discovery by SynSurr:", length(index2), "\n")
index <- c(index1, index2)
cat("Number of marginal SNPs recovered:", sum(index1 %in% index2),"\n")
cat("Number of New Discovery:", sum(!(index2 %in% index1)),"\n")
cat("Average Chisq of marginal GWAS:", mean((result$marginal.beta[index]/result$marginal.se[index])^2),"\n")
cat("Average Chisq of SynSurr:", mean((result$bi.beta[index]/result$bi.se[index])^2),"\n")
cat("RE (Mean Square Standard Error)", mean((result$marginal.se[index])^2/(result$bi.se[index])^2))
```
```{r}
#library(hudson)
bim <- read.table("~/Desktop/SyntheticSurrogateAnalysis/Data/final.bim", header = TRUE)
result <- result %>% inner_join(bim, by = "rsid")

write.csv(result %>% filter(marginal.p<1e-5|bi.p<1e-5) %>% select(rsid, CHR, BP, Ref, Alt, marginal.beta,
                                                                  marginal.se, marginal.p, bi.beta,
                                                                  bi.se, bi.p), file = "small_p.csv",
          row.names = FALSE, quote = FALSE)

result <- result %>% rename(SNP = rsid) %>% left_join(bim)
gwas.b <- result %>% select(SNP, CHR, POS, marginal.p) %>% rename(pvalue = marginal.p)
gwas.t <- result %>% select(SNP, CHR, POS, bi.p) %>% rename(pvalue = bi.p)
ggmirror(top=gwas.t, bottom=gwas.b, tline=5e-8, bline=5e-8, toptitle="SynSurr GWAS", bottomtitle = "Standard GWAS", chrcolor1 = "#00FF00", chrcolor2 = "#006600", chrcolor4 = "#0000CC", chrcolor3 = "#0099FF", file = "arms_miami")
```

# Gynoid total mass (23265)
```{r}
pheno_id <- "f.23265.2.0"
train <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% out_id) %>% tidyr::drop_na(pheno_id) %>% tidyr::drop_na(all_of(cov_id)) %>% select(pheno_id, cov_id) %>% filter(f.23265.2.0 > 100)
test <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% in_id) %>% tidyr::drop_na(all_of(cov_id))%>% select(f.eid,pheno_id, cov_id)  %>% tidyr::drop_na(pheno_id) %>% filter(f.23265.2.0 > 100)

# Random Forest model
model.rf <- ranger::ranger(
  data = train,
  as.formula(paste0(pheno_id, "~."))
)

yhat <- predict(model.rf, data = train %>% select(-pheno_id))$predictions
train$yhat <- yhat
p1 <- train %>% rename(pheno = pheno_id) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 25, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("Model-building dataset")+xlim(c(0,30))+ylim(c(0,30))

yhat <- predict(model.rf, data = test %>% select(-f.eid,-pheno_id))$predictions
test$yhat <- yhat
p2 <- test %>% rename(pheno = pheno_id) %>% filter(!is.na(pheno)) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 25, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("GWAS dataset")+xlim(c(0,30))+ylim(c(0,30))

ggpubr::ggarrange(p1, p2)
```

```{r}
result <- readRDS(paste0("~/Desktop/SyntheticSurrogateAnalysis/Data/pheno=", pheno_id, "_result.rds"))
result[,2:7] <- result[,2:7] %>% mutate_if(is.character, as.numeric)

index1 <- which(result$marginal.p<5e-8)
cat ("Total Number of Discovery by marginal GWAS:", length(index1), "\n")
index2 <- which(result$bi.p<5e-8)
cat ("Total Number of Discovery by SynSurr:", length(index2), "\n")
index <- c(index1, index2)
cat("Number of marginal SNPs recovered:", sum(index1 %in% index2),"\n")
cat("Number of New Discovery:", sum(!(index2 %in% index1)),"\n")
cat("Average Chisq of marginal GWAS:", mean((result$marginal.beta[index]/result$marginal.se[index])^2),"\n")
cat("Average Chisq of SynSurr:", mean((result$bi.beta[index]/result$bi.se[index])^2),"\n")
cat("RE (Mean Square Standard Error)", mean((result$marginal.se[index])^2/(result$bi.se[index])^2))
```
```{r}
#library(hudson)
result <- result %>% inner_join(bim, by = "rsid")

write.csv(result %>% filter(marginal.p<1e-5|bi.p<1e-5) %>% select(rsid, CHR, BP, Ref, Alt, marginal.beta,
                                                                  marginal.se, marginal.p, bi.beta,
                                                                  bi.se, bi.p), file = "small_p.csv",
          row.names = FALSE, quote = FALSE)
colnames(bim) = c("CHR", "SNP", "POS")
result <- result %>% rename(SNP = rsid) %>% left_join(bim)
gwas.b <- result %>% select(SNP, CHR, POS, marginal.p) %>% rename(pvalue = marginal.p)
gwas.t <- result %>% select(SNP, CHR, POS, bi.p) %>% rename(pvalue = bi.p)
ggmirror(top=gwas.t, bottom=gwas.b, tline=5e-8, bline=5e-8, toptitle="SynSurr GWAS", bottomtitle = "Standard GWAS", chrcolor1 = "#00FF00", chrcolor2 = "#006600", chrcolor4 = "#0000CC", chrcolor3 = "#0099FF", file = "gynoid_miami")
```



# Total mass (23283)
```{r}
setwd("/Users/jianhuigao/Desktop/SyntheticSurrogateAnalysis/Data/")
pheno_id <- "f.23283.2.0"
train <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% out_id) %>% tidyr::drop_na(pheno_id) %>% tidyr::drop_na(all_of(cov_id)) %>% select(pheno_id, cov_id) %>% filter(f.23283.2.0 > 100)
test <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% in_id) %>% tidyr::drop_na(all_of(cov_id))%>% select(f.eid,pheno_id, cov_id)  %>% tidyr::drop_na(pheno_id) %>% filter(f.23283.2.0 > 100)

# Random Forest model
model.rf <- ranger::ranger(
  data = train,
  as.formula(paste0(pheno_id, "~."))
)

yhat <- predict(model.rf, data = train %>% select(-pheno_id))$predictions
train$yhat <- yhat
p1 <- train %>% rename(pheno = pheno_id) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 150, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("Model-building dataset")+xlim(c(0,160))+ylim(c(0,160))

yhat <- predict(model.rf, data = test %>% select(-f.eid,-pheno_id))$predictions
test$yhat <- yhat
p2 <- test %>% rename(pheno = pheno_id) %>% filter(!is.na(pheno)) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 150, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("GWAS dataset")+xlim(c(0,160))+ylim(c(0,160))

ggpubr::ggarrange(p1, p2)
```

```{r}
result <- readRDS(paste0("~/Desktop/SyntheticSurrogateAnalysis/Data/pheno=", pheno_id, "_result.rds"))
result[,2:7] <- result %>% select(-rsid) %>% mutate_if(is.character, as.numeric)

index1 <- which(result$marginal.p<5e-8)
cat ("Total Number of Discovery by marginal GWAS:", length(index1), "\n")
index2 <- which(result$bi.p<5e-8)
cat ("Total Number of Discovery by SynSurr:", length(index2), "\n")
index <- c(index1, index2)
cat("Number of marginal SNPs recovered:", sum(index1 %in% index2),"\n")
cat("Number of New Discovery:", sum(!(index2 %in% index1)),"\n")
cat("Average Chisq of marginal GWAS:", mean((result$marginal.beta[index]/result$marginal.se[index])^2),"\n")
cat("Average Chisq of SynSurr:", mean((result$bi.beta[index]/result$bi.se[index])^2),"\n")
cat("RE (Mean Square Standard Error)", mean((result$marginal.se[index])^2/(result$bi.se[index])^2))
```

```{r}
#library(hudson)
result <- result %>% inner_join(bim, by = "rsid")

write.csv(result %>% filter(marginal.p<1e-5|bi.p<1e-5) %>% select(rsid, CHR, BP, Ref, Alt, marginal.beta,
                                                                  marginal.se, marginal.p, bi.beta,
                                                                  bi.se, bi.p), file = "small_p.csv",
          row.names = FALSE, quote = FALSE)
qqman::manhattan(result %>% select(SNP, CHR, POS, bi.p) %>% rename(pvalue = bi.p)%>% filter(pvalue<0.001))

gwas.b <- result %>% select(SNP, CHR, POS, marginal.p) %>% rename(pvalue = marginal.p)
gwas.t <- result %>% select(SNP, CHR, POS, bi.p) %>% rename(pvalue = bi.p)
ggmirror(top=gwas.t, bottom=gwas.b, tline=5e-8, bline=5e-8, toptitle="SynSurr GWAS", bottomtitle = "Standard GWAS", chrcolor1 = "#00FF00", chrcolor2 = "#006600", chrcolor4 = "#0000CC", chrcolor3 = "#0099FF", file = "total_miami")
```

# Legs total mass
```{r}
pheno_id <- "f.23277.2.0"
train <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% out_id) %>% tidyr::drop_na(pheno_id) %>% tidyr::drop_na(all_of(cov_id)) %>% select(pheno_id, cov_id) %>% filter(f.23277.2.0 > 100)
test <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% in_id) %>% tidyr::drop_na(all_of(cov_id))%>% select(f.eid,pheno_id, cov_id)  %>% tidyr::drop_na(pheno_id) %>% filter(f.23277.2.0 > 100)

# Random Forest model
model.rf <- ranger::ranger(
  data = train,
  as.formula(paste0(pheno_id, "~."))
)

yhat <- predict(model.rf, data = train %>% select(-pheno_id))$predictions
train$yhat <- yhat
p1 <- train %>% rename(pheno = pheno_id) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 55, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("Model-building dataset")+xlim(c(0,60))+ylim(c(0,60))

yhat <- predict(model.rf, data = test %>% select(-f.eid,-pheno_id))$predictions
test$yhat <- yhat
p2 <- test %>% rename(pheno = pheno_id) %>% filter(!is.na(pheno)) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 55, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("GWAS dataset")+xlim(c(0,60))+ylim(c(0,60))

ggpubr::ggarrange(p1, p2)
```
```{r}
result <- readRDS(paste0("~/Desktop/SyntheticSurrogateAnalysis/Data/pheno=", pheno_id, "_result.rds"))
result[,2:7] <- result %>% select(-rsid) %>% mutate_if(is.character, as.numeric)

index1 <- which(result$marginal.p<5e-8)
cat ("Total Number of Discovery by marginal GWAS:", length(index1), "\n")
index2 <- which(result$bi.p<5e-8)
cat ("Total Number of Discovery by SynSurr:", length(index2), "\n")
index <- c(index1, index2)
cat("Number of marginal SNPs recovered:", sum(index1 %in% index2),"\n")
cat("Number of New Discovery:", sum(!(index2 %in% index1)),"\n")
cat("Average Chisq of marginal GWAS:", mean((result$marginal.beta[index]/result$marginal.se[index])^2),"\n")
cat("Average Chisq of SynSurr:", mean((result$bi.beta[index]/result$bi.se[index])^2),"\n")
cat("RE (Mean Square Standard Error)", mean((result$marginal.se[index])^2/(result$bi.se[index])^2))
```
```{r}
#library(hudson)
result <- result %>% inner_join(bim, by = "rsid")

write.csv(result %>% filter(marginal.p<1e-5|bi.p<1e-5) %>% select(rsid, CHR, BP, Ref, Alt, marginal.beta,
                                                                  marginal.se, marginal.p, bi.beta,
                                                                  bi.se, bi.p), file = "small_p.csv",
          row.names = FALSE, quote = FALSE)
result <- result %>% rename(SNP = rsid) %>% left_join(bim)
gwas.b <- result %>% select(SNP, CHR, POS, marginal.p) %>% rename(pvalue = marginal.p)
gwas.t <- result %>% select(SNP, CHR, POS, bi.p) %>% rename(pvalue = bi.p)
ggmirror(top=gwas.t, bottom=gwas.b, tline=5e-8, bline=5e-8, toptitle="SynSurr GWAS", bottomtitle = "Standard GWAS", chrcolor1 = "#00FF00", chrcolor2 = "#006600", chrcolor4 = "#0000CC", chrcolor3 = "#0099FF", file = "arms_miami")
```

# Trunk total mass (23287)
```{r}
pheno_id <- "f.23287.2.0"
train <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% out_id) %>% tidyr::drop_na(pheno_id) %>% tidyr::drop_na(all_of(cov_id)) %>% select(pheno_id, cov_id) %>% filter(f.23287.2.0 > 100)
test <- file %>% inner_join(white) %>% filter(!is.na(f.22006.0.0)) %>% filter(f.eid %in% in_id) %>% tidyr::drop_na(all_of(cov_id))%>% select(f.eid,pheno_id, cov_id)  %>% tidyr::drop_na(pheno_id) %>% filter(f.23287.2.0 > 100)

# Random Forest model
model.rf <- ranger::ranger(
  data = train,
  as.formula(paste0(pheno_id, "~."))
)

yhat <- predict(model.rf, data = train %>% select(-pheno_id))$predictions
train$yhat <- yhat
p1 <- train %>% rename(pheno = pheno_id) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 95, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("Model-building dataset")+xlim(c(0,100))+ylim(c(0,100))

yhat <- predict(model.rf, data = test %>% select(-f.eid,-pheno_id))$predictions
test$yhat <- yhat
p2 <- test %>% rename(pheno = pheno_id) %>% filter(!is.na(pheno)) %>% mutate(density = get_density(pheno/1000, yhat/1000)) %>% ggplot(aes(x = pheno/1000, y = yhat/1000, color = density)) + geom_point(alpha = 0.2) + xlab("Observed mass (kg)") + ylab("Predicted mass (kg)") +geom_smooth(method = "lm")+ ggpubr::stat_regline_equation(label.y = 95, aes(label = ..rr.label..))+scale_color_gradient(low = "red", high = "yellow", na.value = NA)+ theme_bw() + ggtitle("GWAS dataset")+xlim(c(0,100))+ylim(c(0,100))

ggpubr::ggarrange(p1, p2)
```
```{r}
result <- readRDS(paste0("~/Desktop/SyntheticSurrogateAnalysis/Data/pheno=", pheno_id, "_result.rds"))
result[,2:7] <- result %>% select(-rsid) %>% mutate_if(is.character, as.numeric)

index1 <- which(result$marginal.p<5e-8)
cat ("Total Number of Discovery by marginal GWAS:", length(index1), "\n")
index2 <- which(result$bi.p<5e-8)
cat ("Total Number of Discovery by SynSurr:", length(index2), "\n")
index <- c(index1, index2)
cat("Number of marginal SNPs recovered:", sum(index1 %in% index2),"\n")
cat("Number of New Discovery:", sum(!(index2 %in% index1)),"\n")
cat("Average Chisq of marginal GWAS:", mean((result$marginal.beta[index]/result$marginal.se[index])^2),"\n")
cat("Average Chisq of SynSurr:", mean((result$bi.beta[index]/result$bi.se[index])^2),"\n")
cat("RE (Mean Square Standard Error)", mean((result$marginal.se[index])^2/(result$bi.se[index])^2))
```
```{r}
#library(hudson)
result <- result %>% inner_join(bim, by = "rsid")

write.csv(result %>% filter(marginal.p<1e-5|bi.p<1e-5) %>% select(rsid, CHR, BP, Ref, Alt, marginal.beta,
                                                                  marginal.se, marginal.p, bi.beta,
                                                                  bi.se, bi.p), file = "small_p.csv",
          row.names = FALSE, quote = FALSE)
result <- result %>% rename(SNP = rsid) %>% left_join(bim)
gwas.b <- result %>% select(SNP, CHR, POS, marginal.p) %>% rename(pvalue = marginal.p)
gwas.t <- result %>% select(SNP, CHR, POS, bi.p) %>% rename(pvalue = bi.p)
ggmirror(top=gwas.t, bottom=gwas.b, tline=5e-8, bline=5e-8, toptitle="SynSurr GWAS", bottomtitle = "Standard GWAS", chrcolor1 = "#00FF00", chrcolor2 = "#006600", chrcolor4 = "#0000CC", chrcolor3 = "#0099FF", file = "trunk_miami")
```